// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	pedalea "github.com/tanaxer01/pedalea/pkg/pedalea"
)

// BikeRepo is an autogenerated mock type for the BikeRepo type
type BikeRepo struct {
	mock.Mock
}

// GetBikeByID provides a mock function with given fields: bikeID
func (_m *BikeRepo) GetBikeByID(bikeID int) (*pedalea.Bike, error) {
	ret := _m.Called(bikeID)

	if len(ret) == 0 {
		panic("no return value specified for GetBikeByID")
	}

	var r0 *pedalea.Bike
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*pedalea.Bike, error)); ok {
		return rf(bikeID)
	}
	if rf, ok := ret.Get(0).(func(int) *pedalea.Bike); ok {
		r0 = rf(bikeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pedalea.Bike)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(bikeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBike provides a mock function with given fields: bikeID, data
func (_m *BikeRepo) UpdateBike(bikeID int, data pedalea.BikeData) error {
	ret := _m.Called(bikeID, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBike")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, pedalea.BikeData) error); ok {
		r0 = rf(bikeID, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBikeRepo creates a new instance of BikeRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBikeRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *BikeRepo {
	mock := &BikeRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
