// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	pedalea "github.com/tanaxer01/pedalea/pkg/pedalea"
)

// RentalRepo is an autogenerated mock type for the RentalRepo type
type RentalRepo struct {
	mock.Mock
}

// GetRentalByUserID provides a mock function with given fields: ID
func (_m *RentalRepo) GetRentalByUserID(ID int) (*pedalea.Rental, error) {
	ret := _m.Called(ID)

	if len(ret) == 0 {
		panic("no return value specified for GetRentalByUserID")
	}

	var r0 *pedalea.Rental
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*pedalea.Rental, error)); ok {
		return rf(ID)
	}
	if rf, ok := ret.Get(0).(func(int) *pedalea.Rental); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pedalea.Rental)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertRental provides a mock function with given fields: data
func (_m *RentalRepo) InsertRental(data pedalea.RentalData) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for InsertRental")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(pedalea.RentalData) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListOverlappingRentals provides a mock function with given fields: userID, bikeID
func (_m *RentalRepo) ListOverlappingRentals(userID int, bikeID int) ([]pedalea.Rental, error) {
	ret := _m.Called(userID, bikeID)

	if len(ret) == 0 {
		panic("no return value specified for ListOverlappingRentals")
	}

	var r0 []pedalea.Rental
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]pedalea.Rental, error)); ok {
		return rf(userID, bikeID)
	}
	if rf, ok := ret.Get(0).(func(int, int) []pedalea.Rental); ok {
		r0 = rf(userID, bikeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pedalea.Rental)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(userID, bikeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUserRentals provides a mock function with given fields: userID
func (_m *RentalRepo) ListUserRentals(userID int) ([]pedalea.Rental, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserRentals")
	}

	var r0 []pedalea.Rental
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]pedalea.Rental, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) []pedalea.Rental); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pedalea.Rental)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRental provides a mock function with given fields: userID, data
func (_m *RentalRepo) UpdateRental(userID int, data pedalea.RentalData) error {
	ret := _m.Called(userID, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRental")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, pedalea.RentalData) error); ok {
		r0 = rf(userID, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRentalRepo creates a new instance of RentalRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRentalRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *RentalRepo {
	mock := &RentalRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
