// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	pedalea "github.com/tanaxer01/pedalea/pkg/pedalea"
)

// Auth is an autogenerated mock type for the Auth type
type Auth struct {
	mock.Mock
}

// GenerateJwtToken provides a mock function with given fields: claims
func (_m *Auth) GenerateJwtToken(claims pedalea.UserClaim) (string, error) {
	ret := _m.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for GenerateJwtToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(pedalea.UserClaim) (string, error)); ok {
		return rf(claims)
	}
	if rf, ok := ret.Get(0).(func(pedalea.UserClaim) string); ok {
		r0 = rf(claims)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(pedalea.UserClaim) error); ok {
		r1 = rf(claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuth creates a new instance of Auth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *Auth {
	mock := &Auth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
