// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	pedalea "github.com/tanaxer01/pedalea/pkg/pedalea"
)

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

// GetUserByEmail provides a mock function with given fields: email
func (_m *UserRepo) GetUserByEmail(email string) (*pedalea.User, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *pedalea.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*pedalea.User, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *pedalea.User); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pedalea.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ID
func (_m *UserRepo) GetUserByID(ID int) (*pedalea.User, error) {
	ret := _m.Called(ID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *pedalea.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*pedalea.User, error)); ok {
		return rf(ID)
	}
	if rf, ok := ret.Get(0).(func(int) *pedalea.User); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pedalea.User)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertUser provides a mock function with given fields: data
func (_m *UserRepo) InsertUser(data *pedalea.InsertUser) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for InsertUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*pedalea.InsertUser) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUser provides a mock function with given fields: ID, data
func (_m *UserRepo) UpdateUser(ID int, data pedalea.UserData) error {
	ret := _m.Called(ID, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, pedalea.UserData) error); ok {
		r0 = rf(ID, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
